{application,iso_filter,
             [{description,"Emergence filter agent for ISO standards (iso.org)"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{iso_filter_app,[]}},
              {applications,[kernel,stdlib,em_filter]},
              {env,[]},
              {modules,[iso_filter_app]},
              {licenses,["Apache-2.0"]},
              {links,[{"GitHub",
                       "https://github.com/EmergenceSystem/iso_filter"}]}]}.
